# image: java:8
image: qlik/gradle

pipelines:
  default:
    - step:
        script:
          - gradle clean test
          - gradle reportsToS3 -Dno-fail-version-conflict=true
          # - git remote add github-clone https://github.com/tioga/dev.git
          # - git push github-clone
          